sudo: false
language: node_js
script: "./script/ci"
cache:
  yarn: true
  directories:
    - node_modules/
node_js:
  - "12"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  matrix:
    - TARGET=node
    - TARGET=browser
